# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 885380bfa96eda9c3a4fdb56a5e8eaf8d4a9a9a28fc6a40d033af17339a26ca249cfeed6b30781edd81a64f64dc9ae646f477f632c7d2d77882335ead84ff7bb

test:
  secret_key_base: aa3a3d7ccde9e90ce8ef9644108703f9aa5377ebb5ca3a952afb4134298d1838391dc9617f6c63a0154c89461892704dcb2656d3025fb4df7b85abc906589098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
