# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d25ce7a211572895a1f7d26da06c65f07b12796c7216a10b8cd800309cf778471ad18012b8b93395b6ae240c6ff909a3f217892b7b63e8285f3b584a43f41a

test:
  secret_key_base: f542137c2564cd0e0e3e8a83cef266e26e389585c728ba4b00994470ccd84b9fac770b990a5dfa1a478c5ba6b2a89b0b5d60ec3336e07083ada88b83cc5e1c4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
