# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ed991348c5044d1a247af66d6e6ebcf062c8e3853f6876ac5b78be465ecb21254f91b94d6f1ae9ea20e5c3b9b5d8fbc9e2d0b63b973682efd100eefa4a2f98

test:
  secret_key_base: 05a0293c72680e83c65e61cacc515c230c5229ac8872a214e8d628a608b0c004b9a32e0573879071c7b6a377a4d62d77fbe7cb795c7775a62033a12dfacfae03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
