# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa92b330dfcc0c342ff7abf641d7ed165918a9c93d2f154c8b2aa7c1b6ca852a926710596a302b57f49bb86d0226655c45c437aa58e14d04bf83ba9cf02e45f6

test:
  secret_key_base: 34325a4d3d92bca00bc7d34a69b31596b5a797f8975114084b0764a0ae9a1f28e3e74d22291778037f8e73d64b6ca2708b6f6b3789b0f0a6f2818d5f0bd99165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
