# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3632e92432fd15c6a681aaea1ed419fc59191332c6d62f9b9540b60228066c079f3ec14a6115604ff15932508b2ca75a696cd30c4c59a6a7bdf9593c02d0c3a

test:
  secret_key_base: 3214908e89f853e9daceac5cad58d3a78a9f1ace366698181523d364c6616ae34d42610c341bb9755dc59eecbb4367e066a681cc06c49d4f01b72e0e27f4a1dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
