# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d51153f068b3a45d7622a43830e857715a8dd9f166b8be87ced4f50d7776d615569b7ee6bb8acb4d87c256f3e0997f48fe93e62225fdab0ed83a773ba94577

test:
  secret_key_base: 9a6e3b40df93829802ce5c04d9e83436234d9bf171f5b7045509e27fea2149379e3604fad98c5206a000891bd5417bc6ec68ccdf9fe7b239d45455c4ab8e179e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
