# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fabdc48e39406bf6aaef78fc1f43134aa606ad82f65fb6225f317ef01f4d29d96b9f999245b30eaf5006816b3c0f5244670cb9682f9d8f9937bba08f287dba

test:
  secret_key_base: e31d49c1a0a75ed0c47aef182fb528428d478b717f7bc864a50dffe157f796bbefaa685d024868a243eb02631257de8ecebe515361959c3338876a41abbc3d10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
