# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18679537cad296fa27dbc3335f15629e0545e12583a69704a2d378227e4ec6d7b82001b230423740fcd47e4de5dd58244699e0a679f3eb1667d03787a3af6dcf

test:
  secret_key_base: 9fe4bdd840ebe992da000428939de288b65d81e3bced866393e505c2e87b8e2266bb58c5f87827458180044d0f1699d0a2479ea1f6d77cb03c5ec845b1431999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
