# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25f10f20ebf720087ab22add05eb89ebac1faf5832aa27127da43d7c0ff4214225b4020b752685e732190420afacafcc716cb1f6ea945a3ce2bf8b5eb3807ddb

test:
  secret_key_base: 22d92a28774197167645ddf32777df803fe62ce03e4fa6e3433045ee4d4da8f254ff88ea88fac993412b334a25b08817a32ff9f0ecdb0f9d5dfbe8f4ec1a8e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
