# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9afe071d43abf3254ef092b0a08193b33dfe9b942c96b2a8f53acfedb7d8f5fcc3b2709231bd11be0df555514ca9af41a5cefbba1b690b969d7a3c9f381002ed

test:
  secret_key_base: d506050b7b6e3c28c99906641f0492089ee5f3e44361db0205cd4e5adfe80e37f0ed7f630fc818a19430d1fd0b1256f23f385d54f6dfd031de131e3e4ecac361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
